server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    # First, try to serve the file directly.
    # If it's a directory, try to serve the index.html file in it.
    # If the file or directory doesn't exist, redirect to the language-specific index.html.
    try_files $uri $uri/ /index.html;
  }

  # Redirect root to the default language
  location = / {
    return 302 $scheme://$http_host/de/;
  }

  # English version
  location /en/ {
    alias /usr/share/nginx/html/en/;
    try_files $uri $uri/ /en/index.html;
  }

  # German version
  location /de/ {
    alias /usr/share/nginx/html/de/;
    try_files $uri $uri/ /de/index.html;
  }

  # Turkish version
  location /tr/ {
    alias /usr/share/nginx/html/tr/;
    try_files $uri $uri/ /tr/index.html;
  }
}
